[app]
address = ":5000"

[db]
#driver = "mysql"
#connect = "root:@tcp(localhost:3306)/ignite?charset=utf8"
driver = "sqlite3"
connect = "./data/ignite.db"

[ss]
image = "goignite/ss-go:latest"

[host]
address = "localhost"
from = 5001
to = 6000
